# Configura l'analizzatore per individuare errori, warning e linter in Dart/Flutter
include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - build/**
    - lib/generated/**
  errors:
    missing_return: error
    dead_code: warning
    todo: ignore
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false

linter:
  rules:
    # Convenzioni di stile
    prefer_single_quotes: true
    always_use_package_imports: true
    avoid_relative_lib_imports: true
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    avoid_unnecessary_containers: true

    # Sicurezza e manutenzione
    avoid_print: true
    avoid_returning_null_for_future: true
    avoid_void_async: true
    use_build_context_synchronously: true
    cancel_subscriptions: true
    close_sinks: true
    dispose_fields: true

    # Miglior leggibilità
    prefer_final_fields: true
    prefer_final_locals: true
    prefer_final_in_for_each: true
    unawaited_futures: true
    require_trailing_commas: true
    directives_ordering: true
    sort_constructors_first: true

    # Performance
    avoid_unnecessary_rebuilds: true
    avoid_init_to_null: true